;;; ini-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ini-mode.el

(autoload 'ini-mode "ini-mode" "\
Major mode for editing Windows-style ini files.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.ini\\'" . ini-mode))
(register-definition-prefixes "ini-mode" '("ini-"))

;;; End of scraped data

(provide 'ini-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ini-mode-autoloads.el ends here
